# Generated by Django 4.1.2 on 2023-01-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_remove_homebanner_serial_no_homebanner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='serial_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
