# Generated by Django 4.1.2 on 2023-01-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_homebanner_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='link',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
