# Generated by Django 4.1.2 on 2023-01-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_websettings_ourteam_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourteam',
            options={'ordering': ['serial_no']},
        ),
        migrations.AddField(
            model_name='ourteam',
            name='serial_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
