# Generated by Django 4.1.2 on 2023-02-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_alter_ourteam_options_ourteam_serial_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websettings',
            options={'verbose_name_plural': 'Web Settings'},
        ),
        migrations.AddField(
            model_name='websettings',
            name='home_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
