# Generated by Django 4.1.2 on 2023-02-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0010_donationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationrequest',
            old_name='contact_noe',
            new_name='contact_no',
        ),
    ]
