# Generated by Django 4.1.2 on 2023-02-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_rename_contact_noe_donationrequest_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='contact_no',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
