# Generated by Django 4.1.2 on 2023-02-04 20:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_alter_donationrequest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='about_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_image'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='about_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
